### ISSUE TITLE
"js9_build -p" - Does not complete

### ISSUE THREAD

**Issue by rainmanh** [Jumpscale/developer#83]
#### Installation information

- jumpscale version:
js9 -- v9.1.1

- operating system:

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

#### Detailed description

__js9_build -p__ fails to complete

#### Steps to reproduce

execute __js9_build -p__

#### Relevant stacktraces

````
[+] start docker jumpscale/base2 -> base3 (port:2222)
[+] authorizing local ssh keys on docker: base3
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDagew2wxPN7hw/56aPY90uyFPzNvxzOlNhwiELcXf8Zj2Rvr2YGkRLSvG3Y8Al1pub6LGV7SbtX3KH2v8mGkxLVwUlGB2bKOhqOhG0+HBLEcSfN1PN9aMpDsEk4PEFx1/35wzdfEKO2jmuSoNH/1AWzen2X8GjmAxNNp6SWYZWPtRdoYBLicpElpNyLkYPkn+zGNcnQGPWytO8Wl+pQTqhXOq80luWPTwaytPIkv/8qjbWkh9ZwX7OdoBWn+wYrhUGUGF/g4XApQ/LCgLAJLOBtFi3NC0m8WnMOYuefbUv3NuHxWjMz1BIuN1bGGggGOfbBqns0HPn0hPPlzCQ4nNP /root/.ssh/g9
[+]   synchronizing developer files
[+]   installing jumpscale core9
[+]   installing binaries files
[+]   initializing jumpscale part3
[+]   cleanup
[+] installing python development environment (needed for certain python packages to install)
[+] installing jumpscale 9 libraries
[+] installing jumpscale 9 portal
[-] line 182: script error, backlog from /tmp/install.log:
[Tue15 15:12] - SystemProcess.py    :661 :j.sal.process                  - INFO     - Checking whether at least 1 processes redis-server are running
                                                        .,,'
                                                   'c.cool,..',,,,,,,.
                                                  'dxocol:l:;,'......';:,.
                                              .lodoclcccc,...............;:.
                                                ':lc:;;;;;.................:;
            JUMPSCALE                         :oc;'..................,'.....,;
            ---------                        olc'.......'...........,. .,:'..:.
                                            ,oc'......;,',..........od.   'c..'
                                            ;o:......l,   ':........dWkkN. ,;..
                                            .d;.....:K. ;   l'......:KMMM: ''.';'
                                             :,.....cNWNMx  .o.......;OWNc,.....,c
                                              c.....'kMMMX   l.........,,......;'c.
                                             l........xNNx...,. 'coxk;',;;'....;xd.
                                            .l..,...........';;;:dkkc::;;,.....'l'
                                             o'x............lldo,.'o,cl:;'...;,;;
                                           ..;dd'...........':'.,lkkk,.....,.l;l
                                       .',,....'l'.co..;'..........'.....;d,;:
                                    ';;..........;;o:c;,dl;oc,'......';;locc;
                                 ,:;...................;;:',:'',,,,,'.      .,.
                              .::.................................            'c
                            .:,...................................           . .l
                          .:,......................................          'l':
                        .;,.......................................            .l.
                     ';c:.........................................          ;:.';
              ',;::::'...........................................            :d;l;.
           'lolclll,,'..............................','..........            .dccco;
          loooool:,'..............................'l'..........     '.       cocclll..
        .lol:;'...................................::.,,'........    .o     .ldcccccccco:
       ,lcc'.........,;...,;.    ................',c:,''........,.  .o   .;;xccccccccld:
        .';ccc:;;,,'.  ...  ..''..             ;;'...............';.c'.''.  ;loolloooo;
                                ..',,,,,,,''...:o,.................c           ....
                                               .;l.................c.
                                                 ;;;;,'..........,;,
                                                    .':ldddoooddl'

[Tue15 15:12] - InstallTools.py     :671 :j.installtools                 - INFO     - None:pull:git@github.com:Jumpscale/portal9.git ->/opt/code/github/jumpscale/portal9
[Tue15 15:12] - InstallTools.py     :740 :j.installtools                 - INFO     - git clone git@github.com:Jumpscale/portal9.git -> /opt/code/github/jumpscale/portal9
[Tue15 15:12] - InstallTools.py     :760 :j.installtools                 - INFO     - mkdir -p /opt/code/github/jumpscale;cd /opt/code/github/jumpscale;git clone  -b master git@github.com:Jumpscale/portal9.git /opt/code/github/jumpscale/portal9
E:Cloning into '/opt/code/github/jumpscale/portal9'...
E:Permission denied (publickey).
E:fatal: Could not read from remote repository.
E:
E:Please make sure you have the correct access rights
E:and the repository exists.
[Tue15 15:12] - InstallTools.py     :671 :j.installtools                 - INFO     - None:pull:https://github.com/Jumpscale/portal9.git ->/opt/code/github/jumpscale/portal9
[Tue15 15:12] - InstallTools.py     :740 :j.installtools                 - INFO     - git clone https://github.com/Jumpscale/portal9.git -> /opt/code/github/jumpscale/portal9
[Tue15 15:12] - InstallTools.py     :760 :j.installtools                 - INFO     - mkdir -p /opt/code/github/jumpscale;cd /opt/code/github/jumpscale;git -c http.sslVerify=false clone  -b master https://github.com/Jumpscale/portal9.git /opt/code/github/jumpscale/portal9
E:Cloning into '/opt/code/github/jumpscale/portal9'...
Reading package lists...
Building dependency tree...
Reading state information...
libsnappy-dev is already the newest version (1.1.3-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Obtaining file:///opt/code/github/jumpscale/portal9
Requirement already satisfied: JumpScale9>=9.1.1 in /opt/code/github/jumpscale/core9 (from JumpScale9Portal==9.1.1)
Requirement already satisfied: redis==2.10.5 in /usr/local/lib/python3.5/dist-packages (from JumpScale9Portal==9.1.1)
Collecting colorlog==2.10.0 (from JumpScale9Portal==9.1.1)
Downloading colorlog-2.10.0-py2.py3-none-any.whl
Requirement already satisfied: pytoml==0.1.14 in /usr/local/lib/python3.5/dist-packages (from JumpScale9Portal==9.1.1)
Requirement already satisfied: ipython==6.1.0 in /usr/local/lib/python3.5/dist-packages (from JumpScale9Portal==9.1.1)
Requirement already satisfied: colored_traceback in /usr/local/lib/python3.5/dist-packages (from JumpScale9Portal==9.1.1)
Requirement already satisfied: pystache==0.5.4 in /usr/local/lib/python3.5/dist-packages (from JumpScale9Portal==9.1.1)
Requirement already satisfied: libtmux==0.7.3 in /usr/local/lib/python3.5/dist-packages (from JumpScale9Portal==9.1.1)
Requirement already satisfied: httplib2==0.10.3 in /usr/local/lib/python3.5/dist-packages (from JumpScale9Portal==9.1.1)
Requirement already satisfied: netaddr==0.7.19 in /usr/local/lib/python3.5/dist-packages (from JumpScale9Portal==9.1.1)
Requirement already satisfied: peewee==2.10.1 in /usr/local/lib/python3.5/dist-packages (from JumpScale9Portal==9.1.1)
Requirement already satisfied: uvloop==0.8.0 in /usr/local/lib/python3.5/dist-packages (from JumpScale9Portal==9.1.1)
Requirement already satisfied: paramiko==2.2.1 in /usr/local/lib/python3.5/dist-packages (from JumpScale9Portal==9.1.1)
Requirement already satisfied: watchdog==0.8.3 in /usr/local/lib/python3.5/dist-packages (from JumpScale9Portal==9.1.1)
Collecting pymux==0.13 (from JumpScale9Portal==9.1.1)
Downloading pymux-0.13-py3-none-any.whl (78kB)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.5/dist-packages (from JumpScale9Portal==9.1.1)
Collecting ipdb==0.10.3 (from JumpScale9Portal==9.1.1)
Downloading ipdb-0.10.3.tar.gz
Collecting requests==2.18.1 (from JumpScale9Portal==9.1.1)
Downloading requests-2.18.1-py2.py3-none-any.whl (88kB)
Requirement already satisfied: cython in /usr/local/lib/python3.5/dist-packages (from JumpScale9Portal==9.1.1)
Collecting pycapnp==0.5.12 (from JumpScale9Portal==9.1.1)
Downloading pycapnp-0.5.12.tar.gz (454kB)
Requirement already satisfied: path.py==10.3.1 in /usr/local/lib/python3.5/dist-packages (from JumpScale9Portal==9.1.1)
Collecting pudb==2017.1.2 (from JumpScale9Portal==9.1.1)
Downloading pudb-2017.1.2.tar.gz (53kB)
Requirement already satisfied: msgpack-python==0.4.8 in /usr/local/lib/python3.5/dist-packages (from JumpScale9Portal==9.1.1)
Requirement already satisfied: pyblake2==0.9.3 in /usr/local/lib/python3.5/dist-packages (from JumpScale9Portal==9.1.1)
Collecting mongoengine==0.10.6 (from JumpScale9Portal==9.1.1)
Downloading mongoengine-0.10.6.tar.gz (346kB)
Requirement already satisfied: gevent==1.2.2 in /usr/local/lib/python3.5/dist-packages (from JumpScale9Portal==9.1.1)
Collecting beaker (from JumpScale9Portal==9.1.1)
Downloading Beaker-1.9.0.tar.gz
Collecting gitlab3==0.5.8 (from JumpScale9Portal==9.1.1)
Downloading gitlab3-0.5.8.tar.gz
Collecting mimeparse==0.1.3 (from JumpScale9Portal==9.1.1)
Downloading mimeparse-0.1.3.tar.gz
Collecting flask (from JumpScale9Portal==9.1.1)
Downloading Flask-0.12.2-py2.py3-none-any.whl (83kB)
Collecting flask-bootstrap (from JumpScale9Portal==9.1.1)
Downloading Flask-Bootstrap-3.3.7.1.tar.gz (456kB)
Requirement already satisfied: GitPython>=2.1.3 in /usr/local/lib/python3.5/dist-packages (from JumpScale9>=9.1.1->JumpScale9Portal==9.1.1)
Requirement already satisfied: click>=6.7 in /usr/local/lib/python3.5/dist-packages (from JumpScale9>=9.1.1->JumpScale9Portal==9.1.1)
Requirement already satisfied: python-dateutil>=2.6.0 in /usr/local/lib/python3.5/dist-packages (from JumpScale9>=9.1.1->JumpScale9Portal==9.1.1)
Requirement already satisfied: toml in /usr/local/lib/python3.5/dist-packages (from JumpScale9>=9.1.1->JumpScale9Portal==9.1.1)
Requirement already satisfied: future>=0.16.0 in /usr/local/lib/python3.5/dist-packages (from JumpScale9>=9.1.1->JumpScale9Portal==9.1.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.5/dist-packages (from JumpScale9>=9.1.1->JumpScale9Portal==9.1.1)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in /usr/local/lib/python3.5/dist-packages (from ipython==6.1.0->JumpScale9Portal==9.1.1)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.5/dist-packages (from ipython==6.1.0->JumpScale9Portal==9.1.1)
Requirement already satisfied: simplegeneric>0.8 in /usr/local/lib/python3.5/dist-packages (from ipython==6.1.0->JumpScale9Portal==9.1.1)
Requirement already satisfied: pygments in /usr/local/lib/python3.5/dist-packages (from ipython==6.1.0->JumpScale9Portal==9.1.1)
Requirement already satisfied: jedi>=0.10 in /usr/local/lib/python3.5/dist-packages (from ipython==6.1.0->JumpScale9Portal==9.1.1)
Requirement already satisfied: decorator in /usr/local/lib/python3.5/dist-packages (from ipython==6.1.0->JumpScale9Portal==9.1.1)
Requirement already satisfied: pexpect; sys_platform != "win32" in /usr/local/lib/python3.5/dist-packages (from ipython==6.1.0->JumpScale9Portal==9.1.1)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.5/dist-packages (from ipython==6.1.0->JumpScale9Portal==9.1.1)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.5/dist-packages (from ipython==6.1.0->JumpScale9Portal==9.1.1)
Requirement already satisfied: cryptography>=1.1 in /usr/local/lib/python3.5/dist-packages (from paramiko==2.2.1->JumpScale9Portal==9.1.1)
Requirement already satisfied: pynacl>=1.0.1 in /usr/local/lib/python3.5/dist-packages (from paramiko==2.2.1->JumpScale9Portal==9.1.1)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/lib/python3/dist-packages (from paramiko==2.2.1->JumpScale9Portal==9.1.1)
Requirement already satisfied: bcrypt>=3.1.3 in /usr/local/lib/python3.5/dist-packages (from paramiko==2.2.1->JumpScale9Portal==9.1.1)
Requirement already satisfied: pathtools>=0.1.1 in /usr/local/lib/python3.5/dist-packages (from watchdog==0.8.3->JumpScale9Portal==9.1.1)
Requirement already satisfied: argh>=0.24.1 in /usr/local/lib/python3.5/dist-packages (from watchdog==0.8.3->JumpScale9Portal==9.1.1)
Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from pymux==0.13->JumpScale9Portal==9.1.1)
Requirement already satisfied: docopt>=0.6.2 in /usr/local/lib/python3.5/dist-packages (from pymux==0.13->JumpScale9Portal==9.1.1)
Requirement already satisfied: pyte>=0.5.1 in /usr/local/lib/python3.5/dist-packages (from pymux==0.13->JumpScale9Portal==9.1.1)
Collecting urllib3<1.22,>=1.21.1 (from requests==2.18.1->JumpScale9Portal==9.1.1)
Downloading urllib3-1.21.1-py2.py3-none-any.whl (131kB)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.5/dist-packages (from requests==2.18.1->JumpScale9Portal==9.1.1)
Collecting idna<2.6,>=2.5 (from requests==2.18.1->JumpScale9Portal==9.1.1)
Downloading idna-2.5-py2.py3-none-any.whl (55kB)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.5/dist-packages (from requests==2.18.1->JumpScale9Portal==9.1.1)
Requirement already satisfied: urwid>=1.1.1 in /usr/local/lib/python3.5/dist-packages (from pudb==2017.1.2->JumpScale9Portal==9.1.1)
Requirement already satisfied: pymongo>=2.7.1 in /usr/local/lib/python3.5/dist-packages (from mongoengine==0.10.6->JumpScale9Portal==9.1.1)
Requirement already satisfied: greenlet>=0.4.10 in /usr/local/lib/python3.5/dist-packages (from gevent==1.2.2->JumpScale9Portal==9.1.1)
Collecting Werkzeug>=0.7 (from flask->JumpScale9Portal==9.1.1)
Downloading Werkzeug-0.12.2-py2.py3-none-any.whl (312kB)
Requirement already satisfied: Jinja2>=2.4 in /usr/local/lib/python3.5/dist-packages (from flask->JumpScale9Portal==9.1.1)
Collecting itsdangerous>=0.21 (from flask->JumpScale9Portal==9.1.1)
Downloading itsdangerous-0.24.tar.gz (46kB)
Collecting dominate (from flask-bootstrap->JumpScale9Portal==9.1.1)
Downloading dominate-2.3.1.tar.gz
Collecting visitor (from flask-bootstrap->JumpScale9Portal==9.1.1)
Downloading visitor-0.1.3.tar.gz
Requirement already satisfied: gitdb2>=2.0.0 in /usr/local/lib/python3.5/dist-packages (from GitPython>=2.1.3->JumpScale9>=9.1.1->JumpScale9Portal==9.1.1)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.5/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython==6.1.0->JumpScale9Portal==9.1.1)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.5/dist-packages (from traitlets>=4.2->ipython==6.1.0->JumpScale9Portal==9.1.1)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.5/dist-packages (from pexpect; sys_platform != "win32"->ipython==6.1.0->JumpScale9Portal==9.1.1)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python3.5/dist-packages (from cryptography>=1.1->paramiko==2.2.1->JumpScale9Portal==9.1.1)
Requirement already satisfied: cffi>=1.7 in /usr/local/lib/python3.5/dist-packages (from cryptography>=1.1->paramiko==2.2.1->JumpScale9Portal==9.1.1)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.5/dist-packages (from Jinja2>=2.4->flask->JumpScale9Portal==9.1.1)
Requirement already satisfied: smmap2>=2.0.0 in /usr/local/lib/python3.5/dist-packages (from gitdb2>=2.0.0->GitPython>=2.1.3->JumpScale9>=9.1.1->JumpScale9Portal==9.1.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.5/dist-packages (from cffi>=1.7->cryptography>=1.1->paramiko==2.2.1->JumpScale9Portal==9.1.1)
Building wheels for collected packages: ipdb, pycapnp, pudb, mongoengine, beaker, gitlab3, mimeparse, flask-bootstrap, itsdangerous, dominate, visitor
Running setup.py bdist_wheel for ipdb: started
Running setup.py bdist_wheel for ipdb: finished with status 'done'
Stored in directory: /root/.cache/pip/wheels/cd/9e/a2/b521d7d90da1032f805e08bf00dce70101ddc39dcb1bb245cb
Running setup.py bdist_wheel for pycapnp: started
Running setup.py bdist_wheel for pycapnp: still running...
Running setup.py bdist_wheel for pycapnp: finished with status 'done'
Stored in directory: /root/.cache/pip/wheels/32/e4/fa/d142c33c810b9c1920361f457877273bd245b1a00d6f7019f8
Running setup.py bdist_wheel for pudb: started
Running setup.py bdist_wheel for pudb: finished with status 'done'
Stored in directory: /root/.cache/pip/wheels/97/72/ab/e609e3090fac6d8d500927555392963bdddb35008edb0a8869
Running setup.py bdist_wheel for mongoengine: started
Running setup.py bdist_wheel for mongoengine: finished with status 'done'
Stored in directory: /root/.cache/pip/wheels/ae/6d/cb/4573bb9aceaed483557761df59571c6a3f108e87a80d2ba03a
Running setup.py bdist_wheel for beaker: started
Running setup.py bdist_wheel for beaker: finished with status 'done'
Stored in directory: /root/.cache/pip/wheels/9c/c8/b2/8bf022b391a0afa9039cd873db5410db0fc2c8871dd4d85bd2
Running setup.py bdist_wheel for gitlab3: started
Running setup.py bdist_wheel for gitlab3: finished with status 'done'
Stored in directory: /root/.cache/pip/wheels/ad/aa/e2/daf9b8edbcf006824ca13c7708729795dc45cf6049bf5e6f02
Running setup.py bdist_wheel for mimeparse: started
Running setup.py bdist_wheel for mimeparse: finished with status 'done'
Stored in directory: /root/.cache/pip/wheels/cb/83/03/ec75acce6afbbecd7aaf161c59554eb64c04fc3bfdeb117a44
Running setup.py bdist_wheel for flask-bootstrap: started
Running setup.py bdist_wheel for flask-bootstrap: finished with status 'done'
Stored in directory: /root/.cache/pip/wheels/45/79/97/ec72a7807d2055114e1291529719be2e00571b1c27167209d7
Running setup.py bdist_wheel for itsdangerous: started
Running setup.py bdist_wheel for itsdangerous: finished with status 'done'
Stored in directory: /root/.cache/pip/wheels/fc/a8/66/24d655233c757e178d45dea2de22a04c6d92766abfb741129a
Running setup.py bdist_wheel for dominate: started
Running setup.py bdist_wheel for dominate: finished with status 'done'
Stored in directory: /root/.cache/pip/wheels/cc/fa/98/d9406331e9f3128e30238191eb899169a69a5a24b43d4d08e3
Running setup.py bdist_wheel for visitor: started
Running setup.py bdist_wheel for visitor: finished with status 'done'
Stored in directory: /root/.cache/pip/wheels/8e/5e/41/c0f515d39b38d492db6d7c12fc4d027385a76fb01aebc9c2b3
Successfully built ipdb pycapnp pudb mongoengine beaker gitlab3 mimeparse flask-bootstrap itsdangerous dominate visitor
Installing collected packages: colorlog, pymux, ipdb, urllib3, idna, requests, pycapnp, pudb, mongoengine, beaker, gitlab3, mimeparse, Werkzeug, itsdangerous, flask, dominate, visitor, flask-bootstrap, JumpScale9Portal
Found existing installation: colorlog 3.0.1
Uninstalling colorlog-3.0.1:
Successfully uninstalled colorlog-3.0.1
Found existing installation: pymux 0.14
Uninstalling pymux-0.14:
Successfully uninstalled pymux-0.14
Found existing installation: urllib3 1.22
Uninstalling urllib3-1.22:
Successfully uninstalled urllib3-1.22
Found existing installation: idna 2.6
Uninstalling idna-2.6:
Successfully uninstalled idna-2.6
Found existing installation: requests 2.18.4
Uninstalling requests-2.18.4:
Successfully uninstalled requests-2.18.4
Found existing installation: pycapnp 0.6.1
Uninstalling pycapnp-0.6.1:
Successfully uninstalled pycapnp-0.6.1
Found existing installation: pudb 2017.1.3
Uninstalling pudb-2017.1.3:
Successfully uninstalled pudb-2017.1.3
Running setup.py develop for JumpScale9Portal
Successfully installed JumpScale9Portal Werkzeug-0.12.2 beaker-1.9.0 colorlog-2.10.0 dominate-2.3.1 flask-0.12.2 flask-bootstrap-3.3.7.1 gitlab3-0.5.8 idna-2.5 ipdb-0.10.3 itsdangerous-0.24 mimeparse-0.1.3 mongoengine-0.10.6 pudb-2017.1.2 pycapnp-0.5.12 pymux-0.13 requests-2.18.1 urllib3-1.21.1 visitor-0.1.3
E:[Tue15 15:14] - SystemProcess.py    :661 :j.sal.process                  - INFO     - Checking whether at least 1 processes redis-server are running
Traceback (most recent call last):
File "/usr/local/bin/js9", line 6, in <module>
exec(compile(open(__file__).read(), __file__, 'exec'))
File "/opt/code/github/jumpscale/core9/cmds/js9", line 19, in <module>
exec(toexec)
File "<string>", line 1, in <module>
File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabRootClass.py", line 65, in apps
self._apps = apps(self.executor, self)
File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/apps/apps.py", line 10, in __init__
base.__init__(self, executor, prefab)
File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabBase.py", line 203, in __init__
exec(do)
File "<string>", line 1, in <module>
File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabBase.py", line 165, in __init__
bin_dir = self.prefab.core.replace("$BINDIR")
File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 370, in replace
text = text.replace("$hostname", self.hostname)
File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 686, in hostname
return self.cache.get("hostname", get)
File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabBase.py", line 149, in cache
self._cache = j.data.cache.get("prefab" + self.id + self.classname, reset=True)
AttributeError: 'Data' object has no attribute 'cache'
'Data' object has no attribute 'cache'
Traceback (most recent call last):
  File "/usr/local/bin/js9_getcode_portal", line 47, in <module>
    j.do.execute("cd %s;sh install.sh" % path)
  File "/opt/code/github/jumpscale/core9/JumpScale9/core/InstallTools.py", line 1899, in execute
    die=die)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorLocal.py", line 41, in execute
    outputStderr=outputStderr, timeout=timeout)
  File "/opt/code/github/jumpscale/core9/JumpScale9/sal/process/SystemProcess.py", line 203, in execute
    raise RuntimeError("Could not execute cmd:\n'%s'\nerr:\n%s" % (command, err))
RuntimeError: Could not execute cmd:
'set -e;cd /opt/code/github/jumpscale/portal9;sh install.sh'
err:
[Tue15 15:14] - SystemProcess.py    :661 :j.sal.process                  - INFO     - Checking whether at least 1 processes redis-server are running
Could not execute cmd:
'set -e;cd /opt/code/github/jumpscale/portal9;sh install.sh'
err:
[Tue15 15:14] - SystemProcess.py    :661 :j.sal.process                  - INFO     - Checking whether at least 1 processes redis-server are running


````

**Comment by rkhamis** [comment]
Already fixed :)

**Comment by rainmanh** [comment]
@rkhamis , where is it fixed? have you committed any changes?
Some more information please?

Many thanks

**Comment by rkhamis** [comment]
Fixed by https://github.com/Jumpscale/lib9/commit/d8287a5ef9bdc0d0c30e3b126f4447cf0c538f59
you'll need to pull https://github.com/Jumpscale/lib9

**Comment by rainmanh** [comment]
ah!
Thanks very much for the information @rkhamis . Very much appreciated.
